"""GitLab integration service - orchestrates test generation and commits."""

from typing import Dict, Any, List, Optional
import httpx
import structlog
from datetime import datetime

from app.services.gitlab_client import GitLabClient
from app.core.config import settings

logger = structlog.get_logger()


class GitLabIntegrationService:
    """Service for orchestrating GitLab integration workflows."""

    def __init__(self, gitlab_client: GitLabClient):
        """
        Initialize integration service.

        Args:
            gitlab_client: Initialized GitLabClient instance
        """
        self.client = gitlab_client

    def _parse_project_url(self, project_url: str) -> str:
        """
        Parse project URL to extract project path.

        Args:
            project_url: Full GitLab project URL (e.g., https://gitlab.com/group/project)

        Returns:
            Project path (e.g., "group/project")
        """
        # Remove protocol and domain
        if "://" in project_url:
            parts = project_url.split("://", 1)[1].split("/", 1)
            if len(parts) > 1:
                return parts[1].rstrip("/")
        return project_url.rstrip("/")

    def _generate_branch_name(self, prefix: str = "feature/tests") -> str:
        """
        Generate unique branch name.

        Args:
            prefix: Branch name prefix

        Returns:
            Branch name like "feature/tests-20241205-143022"
        """
        timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
        return f"{prefix}-{timestamp}"

    def _format_commit_message(
        self,
        test_type: str,
        spec_path: str,
        files_count: int,
        endpoints_covered: Optional[int] = None,
    ) -> str:
        """
        Format commit message according to TestOps Copilot standards.

        Args:
            test_type: Type of tests (api, ui, manual)
            spec_path: Path to specification file
            files_count: Number of generated test files
            endpoints_covered: Number of endpoints covered (optional)

        Returns:
            Formatted commit message
        """
        prefix = settings.GITLAB_COMMIT_PREFIX
        message = f"{prefix}Add {test_type.upper()} tests from {spec_path}\n\n"
        message += f"Generated by TestOps Copilot\n"
        message += f"• Added {files_count} test file(s)\n"

        if endpoints_covered:
            message += f"• Coverage: {endpoints_covered} endpoint(s)\n"

        message += f"\nChanges:\n"
        message += f"• {settings.GITLAB_TESTS_PATH}{test_type}/ (new files)"

        return message

    async def generate_and_commit_tests(
        self,
        project_url: str,
        spec_path: str,
        test_type: str,
        branch: Optional[str] = None,
        target_branch: Optional[str] = None,
        create_mr: bool = True,
        user_data: Optional[Dict[str, str]] = None,
    ) -> Dict[str, Any]:
        """
        Main workflow: download spec → generate tests → commit to GitLab.

        Args:
            project_url: Full GitLab project URL
            spec_path: Path to specification file in repository
            test_type: Type of tests to generate (api, ui, manual)
            branch: Branch name for commit (auto-generated if not provided)
            target_branch: Target branch for MR (defaults to main)
            create_mr: Whether to create Merge Request
            user_data: Optional user data (email, name) for commit author

        Returns:
            Result with MR URL, branch, and generated files
        """
        try:
            # 1. Parse project URL
            project_id = self._parse_project_url(project_url)
            logger.info("Starting GitLab integration", project_id=project_id, spec_path=spec_path)

            # 2. Get specification file
            target_branch = target_branch or settings.GITLAB_DEFAULT_BRANCH
            spec_content = await self.client.get_file_content(project_id, spec_path, target_branch)
            logger.info("Specification downloaded", size=len(spec_content))

            # 3. Generate tests via core-agent-service
            generated_tests = await self._generate_tests_from_spec(
                spec_content=spec_content,
                spec_path=spec_path,
                test_type=test_type,
            )

            if not generated_tests or not generated_tests.get("files"):
                raise ValueError("No tests were generated")

            # 4. Prepare commit actions
            branch_name = branch or self._generate_branch_name()
            actions = []
            test_files = generated_tests["files"]

            for test_file in test_files:
                file_path = test_file.get("path") or test_file.get("filename", "")
                content = test_file.get("code") or test_file.get("content", "")

                # Ensure path starts with tests/generated/
                if not file_path.startswith(settings.GITLAB_TESTS_PATH):
                    file_path = f"{settings.GITLAB_TESTS_PATH}{test_type}/{file_path}"

                actions.append(
                    {
                        "action": "create",
                        "file_path": file_path,
                        "content": content,
                    }
                )

            logger.info("Prepared commit actions", files_count=len(actions))

            # 5. Create branch if it doesn't exist
            try:
                await self.client.create_branch(project_id, branch_name, target_branch)
                logger.info("Branch created", branch=branch_name)
            except Exception as e:
                logger.warning("Branch creation issue", error=str(e), branch=branch_name)

            # 6. Create commit
            commit_message = self._format_commit_message(
                test_type=test_type,
                spec_path=spec_path,
                files_count=len(actions),
                endpoints_covered=generated_tests.get("endpoints_count"),
            )

            author_email = user_data.get("email") if user_data else None
            author_name = user_data.get("name") if user_data else None

            commit = await self.client.create_commit(
                project_id=project_id,
                branch=branch_name,
                commit_message=commit_message,
                actions=actions,
                author_email=author_email,
                author_name=author_name,
            )

            logger.info("Commit created", commit_id=commit.get("id"))

            # 7. Create Merge Request if requested
            mr_url = None
            if create_mr:
                mr_title = f"{settings.GITLAB_COMMIT_PREFIX}Add {test_type.upper()} tests"
                mr_description = f"Automatically generated tests from `{spec_path}`\n\n"
                mr_description += f"**Test Type:** {test_type.upper()}\n"
                mr_description += f"**Files Generated:** {len(actions)}\n"
                if generated_tests.get("endpoints_count"):
                    mr_description += f"**Endpoints Covered:** {generated_tests['endpoints_count']}\n"

                mr = await self.client.create_merge_request(
                    project_id=project_id,
                    source_branch=branch_name,
                    target_branch=target_branch,
                    title=mr_title,
                    description=mr_description,
                )

                # Construct MR URL
                project_info = await self.client.get_project(project_id)
                web_url = project_info.get("web_url", project_url)
                mr_url = f"{web_url}/-/merge_requests/{mr['iid']}"

                logger.info("Merge Request created", mr_url=mr_url)

            # 8. Return result
            return {
                "success": True,
                "merge_request_url": mr_url,
                "branch": branch_name,
                "commit_id": commit.get("id"),
                "generated_files": [action["file_path"] for action in actions],
                "coverage_summary": {
                    "endpoints_covered": generated_tests.get("endpoints_count", 0),
                    "tests_generated": len(actions),
                    "estimated_coverage": generated_tests.get("coverage_percentage", "N/A"),
                },
            }

        except Exception as e:
            logger.error("Failed to generate and commit tests", error=str(e), exc_info=True)
            raise

    async def _generate_tests_from_spec(
        self, spec_content: str, spec_path: str, test_type: str
    ) -> Dict[str, Any]:
        """
        Generate tests from specification content via core-agent-service.

        Args:
            spec_content: Content of specification file
            spec_path: Path to specification (for context)
            test_type: Type of tests to generate

        Returns:
            Generated test files and metadata
        """
        # Use core-agent-service to generate tests from spec
        # First parse the spec, then generate description, then generate code
        async with httpx.AsyncClient(timeout=300.0) as client:
            try:
                # Step 1: Parse spec via spec-parser-service
                import io
                file_bytes = spec_content.encode("utf-8")
                files = {"file": (spec_path.split("/")[-1], io.BytesIO(file_bytes), "application/yaml")}
                
                parse_response = await client.post(
                    f"{settings.SPEC_PARSER_URL}/api/v1/parse/openapi",
                    files=files,
                )
                parse_response.raise_for_status()
                parsed_spec = parse_response.json()

                # Step 2: Create description from parsed spec
                endpoints = parsed_spec.get("endpoints", [])
                if not endpoints:
                    raise ValueError("No endpoints found in specification")

                # Create description from endpoints
                description_parts = [f"Generate {test_type.upper()} tests for the following API endpoints:"]
                for endpoint in endpoints[:20]:  # Limit to first 20 endpoints
                    method = endpoint.get("method", "GET")
                    path = endpoint.get("path", "")
                    summary = endpoint.get("summary", "")
                    description_parts.append(f"- {method} {path}: {summary}")

                description = "\n".join(description_parts)

                # Step 3: Generate test case via core-agent-service
                # We'll use the existing generate endpoint but with spec content
                generate_response = await client.post(
                    f"{settings.CORE_AGENT_URL}/api/v1/generate/test-case",
                    json={
                        "description": description,
                        "test_type": test_type,
                        "feature": "API Tests",
                        "story": f"Tests from {spec_path}",
                        "priority": "NORMAL",
                    },
                    headers={"X-API-Key": "internal"},  # Internal call
                    timeout=180.0,
                )
                generate_response.raise_for_status()
                task_response = generate_response.json()
                task_id = task_response.get("task_id")

                # Step 4: Wait for task completion and get result
                import asyncio
                max_wait = 300  # 5 minutes
                wait_interval = 2
                elapsed = 0

                while elapsed < max_wait:
                    await asyncio.sleep(wait_interval)
                    elapsed += wait_interval

                    task_status = await client.get(
                        f"{settings.CORE_AGENT_URL}/api/v1/tasks/{task_id}",
                        headers={"X-API-Key": "internal"},
                    )
                    task_status.raise_for_status()
                    task_data = task_status.json()

                    status = task_data.get("status", "").upper()
                    if status in ["COMPLETED", "SUCCESS"]:
                        # Get artifacts
                        artifacts = task_data.get("artifacts", {})
                        files = artifacts.get("files", [])

                        return {
                            "files": files,
                            "endpoints_count": len(endpoints),
                            "coverage_percentage": "N/A",
                        }
                    elif status in ["FAILED", "ERROR"]:
                        error = task_data.get("error", "Unknown error")
                        raise ValueError(f"Test generation failed: {error}")

                raise TimeoutError("Test generation timed out")

            except httpx.HTTPStatusError as e:
                logger.error(
                    "Failed to generate tests",
                    status=e.response.status_code,
                    error=e.response.text,
                )
                raise ValueError(f"Test generation failed: {e.response.text}")
            except Exception as e:
                logger.error("Unexpected error in test generation", error=str(e), exc_info=True)
                raise

